export default {
  isLock: false,
  notes: [
    {
      category: "기본",
      nickname: "user1",
      title: "예시노트1",
      text: "첫번째 노트입니다",
      theme: "#F4CCCC",
      time: "2020-10-25 Sun",
      isFavoriete: false,
      is_show: false,
      Todo: [],
      checked: [],
      listCount: 1,
      is_bold: false,
      is_under: false,
      is_incli: false,
      imgPath: "",
      contentModal: false,
      lock: false,
      lock_answer: false,
      lock_value: "",
      webCamStart: false,
      lock_modal: false,
      filename: "",
      predictedImage: "",
      imgComment: "인식하지 못하였습니다.",
      emotion: "NoteKnock",
      translatedText: "",
      translateModal: false,
    },
    {
      category: "To-do List",
      nickname: "user2",
      title: "예시노트2",
      text: "카테고리에 따라 바뀌는 내용입니다",
      theme: "#FFF2CC",
      time: "2020-10-25 Sun",
      isFavoriete: false,
      is_show: false,
      Todo: [],
      checked: [],
      listCount: 1,
      is_bold: false,
      is_under: false,
      is_incli: false,
      imgPath: "",
      contentModal: false,
      lock: false,
      lock_answer: false,
      lock_value: "",
      webCamStart: false,
      lock_modal: false,
      filename: "",
      predictedImage: "",
      imgComment: "인식하지 못하였습니다.",
      emotion: "NoteKnock",
      translatedText: "",
      translateModal: false,
    },
  ],
};
